### ISSUE TITLE
Creating New Project Error

### ISSUE THREAD

**Issue by SHEYICROWN01** [jonataslaw/get_cli#102]
Running `flutter create C:\Users\Sheyicrown PC/get_cli_demo` …

$ flutter create --no-pub -i swift -a java --org com.h C:\Users\Sheyicrown PC/get_cli_demo
Multiple output directories specified.
✖  + error_unexpected ShellException(flutter create --no-pub -i swift -a java --org com.h C:\Users\Sheyicrown PC/get_cli_demo, exitCode 2, workingDirectory: C:\Users\Sheyicrown PC\get_cli_demo)

**Comment by schlotterich** [comment]
Same here. I get this error when I try to run "get create folderName" in VS Code
