### ISSUE TITLE
why executed twice

### ISSUE THREAD

**Issue by ifunfly** [jonataslaw/get_cli#108]
![image](https://user-images.githubusercontent.com/42707028/123502208-2c742f80-d67d-11eb-902e-6ca2e4d7a078.png)
![image](https://user-images.githubusercontent.com/42707028/123502229-62191880-d67d-11eb-8406-d8eb2d8e032a.png)

**Comment by jonataslaw** [comment]
Because the dart compiler has this bug, unfortunately it's not something we can fix around here, and this error only occurs on windows

**Comment by ifunfly** [comment]
> Because the dart compiler has this bug, unfortunately it's not something we can fix around here, and this error only occurs on windows

waiting dart
