### ISSUE TITLE
Both Pendantic and Effective Dart have been deprecated

### ISSUE THREAD

**Issue by Illusion47586** [jonataslaw/get_cli#109]
Both [Pendantic](https://pub.dev/packages/pedantic) and [Effective Dart](https://pub.dev/packages/effective_dart) have been deprecated and [Lints](https://pub.dev/packages/lints) is now 'Official Dart lint rules'. 

But this package still provides only those two options for linting.

**Comment by Illusion47586** [comment]
My PR #110 fixes this.

**Comment by jonataslaw** [comment]
Thanks!
