### ISSUE TITLE
can create page without child folder?

### ISSUE THREAD

**Issue by chanthavong** [jonataslaw/get_cli#113]
example
--home
       \---home_controller.dart
       \---home_bindingdart
       \---home_view.dart

**Comment by CpdnCristiano** [comment]
in 
pubspec.yaml
```yaml
get_cli:
  sub_folder: false
 ```

**Comment by hrithikrtiwari** [comment]
For those who have installed get_cli globally, will it work?

**Comment by shinewanna** [comment]
Hello guys, i can't use 
`get_cli:
  sub_folder: false`
flutter pub get failing like below image
<img width="929" alt="Screen Shot 2021-09-20 at 10 55 52 AM" src="https://user-images.githubusercontent.com/39454969/133957127-18fa04a2-6e1d-4d6c-9a61-960dbb8505d0.png">

**Comment by hrithikrtiwari** [comment]
It has to be a separate prop (no indentation). 
```
get_cli:
    sub_folder: false
```

For Example, the packages are above, and get_cli is entirely new dependency below.
Note: Do not forget to `flutter pub get` after this or better `flutter clean` `flutter pub get`

#### Snip shows the structure
![image](https://user-images.githubusercontent.com/42163313/135186162-1c8c76ac-1387-48af-b196-8df393c4a925.png)
