### ISSUE TITLE
Not able to create a sub module under a module

### ISSUE THREAD

**Issue by ubitechdevelopers** [jonataslaw/get_cli#119]
D:\attendance1>get create page:settings on home

The page [settings] already exists, do you want to overwrite it?

  1) Yes!
  2) No
  3) I want to rename
1
✖  + Folder .\lib\app\modules\home\settings not found

Time: 3604 Milliseconds

The page [settings] already exists, do you want to overwrite it?

  1) Yes!
  2) No
  3) I want to rename
1
✖  + Folder .\lib\app\modules\home\settings not found

Time: 4312 Milliseconds

**Comment by ubitechdevelopers** [comment]
only folders are being created and not files

**Comment by syssam** [comment]
any update?

**Comment by deepss1** [comment]
Duplicate of #64 

[Solution / Workaround](https://github.com/jonataslaw/get_cli/issues/64#issuecomment-948264890)

**Comment by CpdnCristiano** [comment]
fix in next versionb
