### ISSUE TITLE
get update - not updating to latest version

### ISSUE THREAD

**Issue by iggymacd** [jonataslaw/get_cli#12]
When I run 'get update', the version remains at 0.11.2. See below for output. OS is Windows 10.

upgrade get_cli
$ pub global activate get_cli
Package get_cli is currently active at version 0.11.2.
Resolving dependencies...
+ ansicolor 1.0.5
+ archive 2.0.13
+ args 1.6.0
+ charcode 1.1.3 (1.2.0-nullsafety available)
+ cli_menu 0.2.3
+ cli_util 0.2.0
+ collection 1.14.13 (1.15.0-nullsafety.2 available)
+ convert 2.1.1
+ crypto 2.1.5
+ get_cli 0.11.2 (1.0.3 available)
+ http 0.12.2
+ http_parser 3.1.4
+ io 0.3.4
+ meta 1.2.3 (1.3.0-nullsafety.2 available)
+ path 1.7.0 (1.8.0-nullsafety available)
+ pedantic 1.9.2 (1.10.0-nullsafety available)
+ process_run 0.10.12+2 (0.10.12+3 available)
+ pub_semver 1.4.4
+ recase 3.0.0
+ source_span 1.7.0 (1.8.0-nullsafety.1 available)
+ string_scanner 1.0.5 (1.1.0-nullsafety available)
+ term_glyph 1.1.0 (1.2.0-nullsafety available)
+ typed_data 1.2.0 (1.3.0-nullsafety.2 available)
+ yaml 2.2.1
Precompiling executables...
Precompiled get_cli:bin\get.
Installed executable get.
Warning: Pub installs executables into C:\Users\DU732RP\AppData\Roaming\Pub\Cache\bin, which is not on your path.
You can fix that by adding that directory to your system's "Path" environment variable.
A web search for "configure windows path" will show you how.
Activated get_cli 0.11.2.
falha ao atualizar
A NEW VERSION IS AVAILABLE!
░██████╗░███████╗████████╗   ░█████╗░██╗░░░░░░██╗
██╔════╝░██╔════╝╚══██╔══╝   ██╔══██╗██║░░░░░░██║
██║░░██╗░█████╗░░░░░██║░░░   ██║░░╚═╝██║░░░░░░██║
██║░░╚██╗██╔══╝░░░░░██║░░░   ██║░░██╗██║░░░░░░██║
╚██████╔╝███████╗░░░██║░░░   ╚█████╔╝███████╗ ██║
░╚═════╝░╚══════╝░░░╚═╝░░░   ░╚════╝░╚══════╝ ╚═╝

Version: 0.11.2
VERSION AVAILABLE: 1.0.3
Run: get update

**Comment by CpdnCristiano** [comment]
Run `flutter pub global activate get_cli`

**Comment by jonataslaw** [comment]
Thanks for inserting the log, but from the log itself it is clear that the update is happening, but that the dart is not configured correctly on your machine, causing it to fail.

Warning: Pub installs executables into C:\Users\DU732RP\AppData\Roaming\Pub\Cache\bin, which is not on your path.
You can fix that by adding that directory to your system's "Path" environment variable.
A web search for "configure windows path" will show you how.

As suggested, look for:
`A web search for "configure windows path" will show you how.`

**Comment by iggymacd** [comment]
Hi,

Thanks for the update. I am not able to modify my path, as this is a work
laptop and the admin team has denied my account access to update path. I
was hoping I could do something manually to put the newer version in the
same location,  but I am not sure if that is possible. In any case, thanks
for responding.

Allan

**Comment by lixun911** [comment]
> When I run 'get update', the version remains at 0.11.2. See below for output. OS is Windows 10.
> 
> upgrade get_cli
> $ pub global activate get_cli
> Package get_cli is currently active at version 0.11.2.
> Resolving dependencies...
> 
> * ansicolor 1.0.5
> * archive 2.0.13
> * args 1.6.0
> * charcode 1.1.3 (1.2.0-nullsafety available)
> * cli_menu 0.2.3
> * cli_util 0.2.0
> * collection 1.14.13 (1.15.0-nullsafety.2 available)
> * convert 2.1.1
> * crypto 2.1.5
> * get_cli 0.11.2 (1.0.3 available)
> * http 0.12.2
> * http_parser 3.1.4
> * io 0.3.4
> * meta 1.2.3 (1.3.0-nullsafety.2 available)
> * path 1.7.0 (1.8.0-nullsafety available)
> * pedantic 1.9.2 (1.10.0-nullsafety available)
> * process_run 0.10.12+2 (0.10.12+3 available)
> * pub_semver 1.4.4
> * recase 3.0.0
> * source_span 1.7.0 (1.8.0-nullsafety.1 available)
> * string_scanner 1.0.5 (1.1.0-nullsafety available)
> * term_glyph 1.1.0 (1.2.0-nullsafety available)
> * typed_data 1.2.0 (1.3.0-nullsafety.2 available)
> * yaml 2.2.1
>   Precompiling executables...
>   Precompiled get_cli:bin\get.
>   Installed executable get.
>   Warning: Pub installs executables into C:\Users\DU732RP\AppData\Roaming\Pub\Cache\bin, which is not on your path.
>   You can fix that by adding that directory to your system's "Path" environment variable.
>   A web search for "configure windows path" will show you how.
>   Activated get_cli 0.11.2.
>   falha ao atualizar
>   A NEW VERSION IS AVAILABLE!
>   ░██████╗░███████╗████████╗   ░█████╗░██╗░░░░░░██╗
>   ██╔════╝░██╔════╝╚══██╔══╝   ██╔══██╗██║░░░░░░██║
>   ██║░░██╗░█████╗░░░░░██║░░░   ██║░░╚═╝██║░░░░░░██║
>   ██║░░╚██╗██╔══╝░░░░░██║░░░   ██║░░██╗██║░░░░░░██║
>   ╚██████╔╝███████╗░░░██║░░░   ╚█████╔╝███████╗ ██║
>   ░╚═════╝░╚══════╝░░░╚═╝░░░   ░╚════╝░╚══════╝ ╚═╝
> 
> Version: 0.11.2
> VERSION AVAILABLE: 1.0.3
> Run: get update

**you have to update dart to 2.10.1**

**Comment by israelhudson** [comment]
i have the same problem but resolve following the next steps

this problem happens because the dart-sdk version is deprecated.

`Package get_cli is currently active at version 0.11.2.
Resolving dependencies...
The current Dart SDK version is 2.7.0.

Because every version of get_cli from git depends on cli_dialog >=0.3.2 which requires SDK version >=2.8.0 <3.0.0,
  get_cli from git is forbidden.
So, because pub global activate depends on get_cli from git, version solving failed.`

- in administrator mode execute on cmd: `choco upgrade dart-sdk`
- get update

Done!

**Comment by hareendranmg** [comment]
It is also happening in Ubuntu 18.04 when updating from **1.3.13 to 1.3.14.**

```
╭─       ~ ─────────────────────────────────────────────────────────────────────────────────────── ✔  at 12:11:00    ─╮
╰─ get update                                                                                                                 ─╯

Upgrading get_cli …

$ pub global activate get_cli
Package get_cli is currently active at version 1.3.13.
Resolving dependencies...
+ _fe_analyzer_shared 12.0.0 (13.0.0 available)
+ analyzer 0.40.6 (0.41.0 available)
+ ansicolor 1.0.5
+ archive 2.0.13
+ args 1.6.0
+ async 2.4.2 (2.5.0-nullsafety.3 available)
+ charcode 1.1.3 (1.2.0-nullsafety.3 available)
+ cli_dialog 0.3.3
+ cli_menu 0.2.3 (0.3.0-nullsafety.0 available)
+ cli_util 0.2.0 (0.3.0-nullsafety.0 available)
+ collection 1.14.13 (1.15.0-nullsafety.5 available)
+ convert 2.1.1 (3.0.0-nullsafety.0 available)
+ crypto 2.1.5
+ dart_style 1.3.9
+ get_cli 1.3.13 (1.3.14 available)
+ glob 1.2.0
+ grapheme_splitter 1.0.0
+ http 0.12.2
+ http_parser 3.1.4 (4.0.0-nullsafety available)
+ intl 0.16.1 (0.17.0-nullsafety.2 available)
+ io 0.3.4
+ js 0.6.2 (0.6.3-nullsafety.3 available)
+ json_ast 1.0.5
+ meta 1.2.3 (1.3.0-nullsafety.6 available)
+ node_interop 1.2.0
+ node_io 1.1.1
+ package_config 1.9.3
+ path 1.7.0 (1.8.0-nullsafety.3 available)
+ pedantic 1.9.2 (1.10.0-nullsafety.3 available)
+ process_run 0.10.12+3 (0.11.2+5 available)
+ pub_semver 1.4.4
+ recase 3.0.1
+ source_span 1.7.0 (1.8.0-nullsafety.4 available)
+ string_scanner 1.0.5 (1.1.0-nullsafety.3 available)
+ term_glyph 1.1.0 (1.2.0-nullsafety.3 available)
+ typed_data 1.2.0 (1.3.0-nullsafety.5 available)
+ version 1.2.0
+ watcher 0.9.7+15
+ yaml 2.2.1 (3.0.0-nullsafety.0 available)
Precompiling executables...
Precompiled get_cli:get.
Installed executable get.
Activated get_cli 1.3.13.
✓ Upgrade complete

There's an update available!
Current installed version: 1.3.13         


░██████╗░███████╗████████╗   ░█████╗░██╗░░░░░░██╗
██╔════╝░██╔════╝╚══██╔══╝   ██╔══██╗██║░░░░░░██║
██║░░██╗░█████╗░░░░░██║░░░   ██║░░╚═╝██║░░░░░░██║
██║░░╚██╗██╔══╝░░░░░██║░░░   ██║░░██╗██║░░░░░░██║
╚██████╔╝███████╗░░░██║░░░   ╚█████╔╝███████╗ ██║
░╚═════╝░╚══════╝░░░╚═╝░░░   ░╚════╝░╚══════╝ ╚═╝


New version available: 1.3.14
Please, run get update

```

Output from flutter doctor

```
╰─ flutter doctor                                                                                                             ─╯
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (not installed)
[✓] Connected device (1 available)
```

Dart Vesion

```
╰─ dart --version                                                                                                             ─╯
Dart SDK version: 2.9.2 (stable) (Wed Aug 26 12:44:28 2020 +0200) on "linux_x64"
```

**Comment by CpdnCristiano** [comment]
Run 
`flutter pub global activate get_cli`

**Comment by hareendranmg** [comment]
> Run
> `flutter pub global activate get_cli`

No change. This is the output.

```
╰─ flutter pub global activate get_cli                                                                                        ─╯
Package get_cli is currently active at version 1.3.14.
Resolving dependencies...
+ _fe_analyzer_shared 12.0.0 (13.0.0 available)
+ analyzer 0.40.6 (0.41.0 available)
+ ansicolor 1.0.5
+ archive 2.0.13
+ args 1.6.0
+ async 2.4.2
+ charcode 1.1.3
+ cli_dialog 0.3.3
+ cli_menu 0.2.3
+ cli_util 0.2.0
+ collection 1.14.13
+ convert 2.1.1
+ crypto 2.1.5
+ dart_style 1.3.9
+ get_cli 1.3.14
+ glob 1.2.0
+ grapheme_splitter 1.0.0
+ http 0.12.2
+ http_parser 3.1.4
+ intl 0.16.1
+ io 0.3.4
+ js 0.6.2
+ json_ast 1.0.5
+ meta 1.2.3
+ node_interop 1.2.0
+ node_io 1.1.1
+ package_config 1.9.3
+ path 1.7.0
+ pedantic 1.9.2
+ process_run 0.11.2+5
+ pub_semver 1.4.4
+ recase 3.0.1
+ source_span 1.7.0
+ string_scanner 1.0.5
+ synchronized 2.2.0+2
+ term_glyph 1.1.0
+ typed_data 1.2.0
+ version 1.2.0
+ watcher 0.9.7+15
+ yaml 2.2.1
Precompiling executables...
Precompiled get_cli:get.
Installed executable get.
Activated get_cli 1.3.14.

╭─       ~ ───────────────────────────────────────────────────────────────────────── ✔  took 21s    at 13:14:32    ─╮
╰─ get -v                                                                                                                     ─╯
░██████╗░███████╗████████╗   ░█████╗░██╗░░░░░░██╗
██╔════╝░██╔════╝╚══██╔══╝   ██╔══██╗██║░░░░░░██║
██║░░██╗░█████╗░░░░░██║░░░   ██║░░╚═╝██║░░░░░░██║
██║░░╚██╗██╔══╝░░░░░██║░░░   ██║░░██╗██║░░░░░░██║
╚██████╔╝███████╗░░░██║░░░   ╚█████╔╝███████╗ ██║
░╚═════╝░╚══════╝░░░╚═╝░░░   ░╚════╝░╚══════╝ ╚═╝

Version: 1.3.13

There's an update available!
Current installed version: 1.3.13         


░██████╗░███████╗████████╗   ░█████╗░██╗░░░░░░██╗
██╔════╝░██╔════╝╚══██╔══╝   ██╔══██╗██║░░░░░░██║
██║░░██╗░█████╗░░░░░██║░░░   ██║░░╚═╝██║░░░░░░██║
██║░░╚██╗██╔══╝░░░░░██║░░░   ██║░░██╗██║░░░░░░██║
╚██████╔╝███████╗░░░██║░░░   ╚█████╔╝███████╗ ██║
░╚═════╝░╚══════╝░░░╚═╝░░░   ░╚════╝░╚══════╝ ╚═╝


New version available: 1.3.14
Please, run get update
```

**Comment by hareendranmg** [comment]
My issue resolved.

I have two flutter installed.
One from snap package and another from manually installed.

I removed the snap flutter and the issue gone.

**Comment by apriliantocecep** [comment]
solved with upgrade dart
```
brew upgrade dart
```

then

```
get update
```

**Comment by MaYunFei** [comment]
> solved with upgrade dart
> 
> ```
> brew upgrade dart
> ```
> 
> then
> 
> ```
> get update
> ```

thanks
