### ISSUE TITLE
How can i  install get_cli. miss binary file. macos monterey 12.0.1 m1  pro

### ISSUE THREAD

**Issue by ifunfly** [jonataslaw/get_cli#143]
How can i  install get_cli. miss binary file. macos monterey 12.0.1 m1  pro
thanks
<img width="1329" alt="1" src="https://user-images.githubusercontent.com/42707028/143727339-2efa9734-7830-49d6-b648-b0991d87845f.png">

**Comment by CpdnCristiano** [comment]
run
```sh
flutter pub global activate get_cli
```

**Comment by ifunfly** [comment]
>same effect                             
<img width="1512" alt="else" src="https://user-images.githubusercontent.com/42707028/144728149-ccb5a5e8-6ea2-4ff0-abbd-dd1919bf2ca3.png">

**Comment by bopo** [comment]
`dart pub global activate get_cli`

**Comment by ifunfly** [comment]
is ok. very thanks.

>
