### ISSUE TITLE
getting Warning: Executable "get" after upgrading to flutter 2.8.0

### ISSUE THREAD

**Issue by Avo-Mandjian** [jonataslaw/get_cli#144]
running flutter pub global activate get_cli is giving me the below error

Warning: Executable "get" runs "bin/get.dart", which was not found in get_cli.
Warning: Executable "getx" runs "bin/get.dart", which was not found in get_cli.

and I am not able to use get or getx commands

**Comment by bopo** [comment]
`dart pub global activate get_cli`
