### ISSUE TITLE
Problem to install get_cli in flutter 2.8.0 get_cli 1.7.1

### ISSUE THREAD

**Issue by brasizza** [jonataslaw/get_cli#147]
flutter pub global activate get_cli

Resolving dependencies...
+ _fe_analyzer_shared 31.0.0 (32.0.0 available)
+ analyzer 2.8.0 (3.0.0 available)
+ ansicolor 2.0.1
+ args 2.3.0
+ async 2.8.2
+ charcode 1.3.1
+ cli_dialog 0.5.0
+ cli_util 0.3.5
+ clock 1.1.0
+ collection 1.15.0
+ convert 3.0.1
+ crypto 3.0.1
+ dart_console 1.0.0
+ dart_style 2.2.0
+ ffi 1.1.2
+ file 6.1.2
+ get_cli 1.7.1
+ glob 2.0.2
+ http 0.13.4
+ http_parser 4.0.0
+ intl 0.17.0
+ matcher 0.12.11
+ meta 1.7.0
+ package_config 2.0.2
+ path 1.8.0
+ process_run 0.12.2+2
+ pub_semver 2.1.0
+ pubspec 2.0.1
+ quiver 3.0.1+1
+ recase 4.0.0
+ source_span 1.8.1
+ stack_trace 1.10.0
+ string_scanner 1.1.0
+ synchronized 3.0.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ uri 1.0.0
+ version 2.0.0
+ watcher 1.0.1
+ win32 2.3.1
+ yaml 3.1.0
Installed executables get and getx.
Warning: Executable "get" runs "bin/get.dart", which was not found in get_cli.
Warning: Executable "getx" runs "bin/get.dart", which was not found in get_cli.
Activated get_cli 1.7.1.

**Comment by AmirVahedix** [comment]
Same for me

**Comment by AmirVahedix** [comment]
`dart pub global activate get_cli`
worked for me

**Comment by brasizza** [comment]
> `dart pub global activate get_cli`

worked like a charm boy. thank you very much!
