### ISSUE TITLE
error code: 1010501 Protocol scheme 'project' is not supported

### ISSUE THREAD

**Issue by meeftah** [jonataslaw/get_cli#167]
As the title says, I got this error when creating a project
`error code: 1010501 Protocol scheme 'project' is not supported`

any suggestion?

**Comment by fahmi277** [comment]
can you explain how to create the project ?

**Comment by meeftah** [comment]
its my bad...it was conflicted with get command from xampp, so i have to use getx command instead of get command

**Comment by Shailendra-3Frames** [comment]
I am facing a similar issue.

I tried: 
`get create page:my_page`

I got this error:
error code: 1010501 Protocol scheme 'page' is not supported

I tried:
`getx create page:my_page`
I got this error:
`zsh: command not found: getx`
