### ISSUE TITLE
import '../../config.dart'; is missing after creating a new "clean" project with get_cli version 1.3.11

### ISSUE THREAD

**Issue by udiedrichsen** [jonataslaw/get_cli#18]
I guess config.dart should be something like that:

enum Environments {
  PRODUCTION,
  QAS,
}

class ConfigEnvironments {
  static Map<String, dynamic> _env = {
    "env": 
      Environments.PRODUCTION
    };

  static Map<String, dynamic> getEnvironments() {
    return _env;
  }
}

**Comment by Katekko** [comment]
The config.dart is the same of config.example.dart. 

But yes, the CLI need to create the config.dart aswell.

**Comment by CpdnCristiano** [comment]
fix on 1.3.12
