### ISSUE TITLE
void Oninit dosen't Working -Please Provide a fix or example on how to use the Controller 

### ISSUE THREAD

**Issue by abdelrahmanelmarakby** [jonataslaw/get_cli#19]
**What I want to help me to use the Controller as I tried the docs and it didn't work with me**

**This is my View**
``` 
class SplashScreenView extends GetView<SplashScreenController> {
  final SplashScreenController c = Get.find();

  Widget build(BuildContext context) {
    return Scaffold(
      body: SplashScreen(
        navigateAfterSeconds: HomeView(),

        //  imageBackground: ,
        seconds: 1,

        image: Image.asset(
          'assets/SplashScreen.png',
          fit: BoxFit.cover,
          height: Get.height,
          width: Get.width,
        ), //     child: ,
        loaderColor: Colors.red,
        loadingText: Text("جاري التحميل..."),
      ),
    );
  }
}
```
**And this my Controller**

``` 
class SplashScreenController extends GetxController {
  @override
  void onInit() {
    FlutterStatusbarManager.setNavigationBarColor(Color(0xfff00),
        animated: true);
    FlutterStatusbarManager.setColor(Color(0xfff00), animated: true);
  }

  @override
  void onReady() {}

  @override
  void onClose() {}
  void Print() => print("clicked");
}
```

**Comment by Katekko** [comment]
Do you have any log about the error?

**Comment by lixun911** [comment]
you don'e need controller for splash screen you just set the timer. unless you waiting for data to load so you need to check the data and you need spinner.

body: dataLoading ? Spinner() : HomeView(),
===================================================
for Splash screen:

void main() {
  runApp(
    GetMaterialApp(
      title: "Application",
      initialRoute: SplashScreenView(),
    ),
  );
}

**Comment by abdelrahmanelmarakby** [comment]
Can you tell me how to navigate to home screen after 5 sec?

> you don'e need controller for splash screen you just set the timer. unless you waiting for data to load so you need to check the data and you need spinner.
> 
> # body: dataLoading ? Spinner() : HomeView(),
> for Splash screen:
> 
> void main() {
> runApp(
> GetMaterialApp(
> title: "Application",
> initialRoute: SplashScreenView(),
> ),
> );
> }

**Comment by lixun911** [comment]
I think you are using SplashScreen package "https://pub.dev/packages/splashscreen" so it suppose to direct you to home screen just import home.dart so can see it. i don't think you need to use get navigate but i'm not sure. 

but to navigate with get:
1- Get.to(HomeView());               // this will keep the previous route in stack so you can go back.
2- Get.off(HomeView());            // this will remove the previous route from stack. example (login screen , splash screen).
3- Get.offAll(HomeView());       // this will remove all previous routes from stack. example (place order process).
4- Get.back();         // so you can go back to previous screen or route.

For reading:
https://github.com/jonataslaw/getx/blob/master/documentation/en_US/route_management.md#route-management

**Comment by CpdnCristiano** [comment]
I believe this problem is best answered in the [getX repository](https://github.com/jonataslaw/getx)

**Comment by CpdnCristiano** [comment]
for this reason I will close this issue
