### ISSUE TITLE
Error creating project: terminal integration windows 11

### ISSUE THREAD

**Issue by ArturAfonso** [jonataslaw/get_cli#209]
I noticed that it is no longer possible to create a project by command line with get_cli in the CMD/vscode terminal in windows 11, when reaching the step to inform the company's domain it does not allow to proceed, it does not matter if you fill in the domain or not, no noticed this problem in linux terminal

-------------

notei não ser mais possivel criar um projeto por linha de comando com o get_cli nos CMD/vscode terminal no windows 11, ao chegar na etapa para informar o dominio da empresa ele nao permite prosseguir, nao importa se vc preencher ou nao o domonio, nao notei este problema no terminal do linux

![Screen Shot 01-12-23 at 01 09 PM](https://user-images.githubusercontent.com/45760522/212120911-ea46e87f-491a-4401-9204-5fc3aa23ba57.PNG)

**Comment by fangjunai** [comment]
try

flutter pub global activate   -sgit "https://github.com/jonataslaw/get_cli.git"

**Comment by ArturAfonso** [comment]
solved, thanks
