### ISSUE TITLE
what is the difference between view and screen?

### ISSUE THREAD

**Issue by jiqimaogou** [jonataslaw/get_cli#22]
```
get create screen:main
```

and

```
get create view:main
```

I saw they generate something similar.

and have not document about screen.

and are you interesting to generate a controller based on http request?

**Comment by CpdnCristiano** [comment]
Screen is for clean architecture users...
Page Is for getx_pattern users

**Comment by CpdnCristiano** [comment]
View, Generate only the view.
Screen generate view, controller and binding
