### ISSUE TITLE
Wrong folder on Generate models

### ISSUE THREAD

**Issue by maares** [jonataslaw/get_cli#23]
Hi,
steps to reproduce:

get create project -> name -> GetX pattern
get create page:posts
get create page:post
get generate model on post with assets/models/model_post.json

Model output is on page "posts"instead of "post".

Thanks for the amazing work!

**Comment by CpdnCristiano** [comment]
As the 2 pages have similar names, the CLI confused I will work to improve the algorithm.
Thank you for your feedback

**Comment by CpdnCristiano** [comment]
Temporary solution
```get generate model on post/ with assets/models/model_post.json ```

**Comment by maares** [comment]
@CpdnCristiano many thanks

**Comment by CpdnCristiano** [comment]
fix on next version
