### ISSUE TITLE
Error Create GetX Pattern

### ISSUE THREAD

**Issue by gdelgado11** [jonataslaw/get_cli#24]
PS C:\Users\Gustavo\androidstudioprojects> get create project
  1) Flutter Project
  2) Get Server
1
? what is the name of the project? juegosx
? What is your company's domain?  example: com.yourcompany  com.senior

Running `flutter create C:\Users\Gustavo\androidstudioprojects/juegosx` …

$ flutter create --org com.senior C:\Users\Gustavo\androidstudioprojects/juegosx
Recreating project ....
Wrote 3 files.

All done!
[✓] Flutter: is fully installed. (Channel master, 1.23.0-14.0.pre.136, on Microsoft Windows [VersiÃ³n 10.0.19041.450], locale es-VE)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.2)
[✓] Chrome - develop for the web: is fully installed.
[✓] Android Studio: is fully installed. (version 4.0)
[✓] VS Code: is fully installed. (version 1.50.0)
[✓] Connected device: is fully installed. (3 available)

In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in .\lib\main.dart.

  1) GetX Pattern (by Kauê)
  2) CLEAN (by Arktekko)
1

Your lib folder is not empty. Are you sure you want to overwrite your project?
WARNING: This action is irreversible

  1) Yes
  2) No
1
✓ Main sample created successfully 👍

Checking project type

Flutter project detected!

Checking project type

Flutter project detected!

✖ Folder app/modules/home not found

✓ main.dart created
✓ app_routes.dart created
✓ app_pages.dart created
✖ Unexpected error occurred:
NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: path

**Comment by gdelgado11** [comment]
If I create the project using CLEAN everything is generated without problems. But with Option 1 GetX Pattern not work.

**Comment by CpdnCristiano** [comment]
which version of Cli are you using?

**Comment by gdelgado11** [comment]
PS C:\Users\Gustavo> get -v
░██████╗░███████╗████████╗   ░█████╗░██╗░░░░░░██╗
██╔════╝░██╔════╝╚══██╔══╝   ██╔══██╗██║░░░░░░██║
██║░░██╗░█████╗░░░░░██║░░░   ██║░░╚═╝██║░░░░░░██║
██║░░╚██╗██╔══╝░░░░░██║░░░   ██║░░██╗██║░░░░░░██║
╚██████╔╝███████╗░░░██║░░░   ╚█████╔╝███████╗ ██║
░╚═════╝░╚══════╝░░░╚═╝░░░   ░╚════╝░╚══════╝ ╚═╝

Version: 1.3.12
With last version 1.3.11 worked, but im apgrade and now not work.

**Comment by daveMcelf** [comment]
+1

got the same error when run `get create page:page_name` on 1.3.12, but downgrade to 1.3.11 working fine

**Comment by gdelgado11** [comment]
Please do you send me how downgrade to 1.3.11 version

**Comment by gdelgado11** [comment]
When I run get create page:home for example i have the same error. Please how i can downgrade to 1.3.11 version.

**Comment by jonataslaw** [comment]
I have no problems using the latest version. What operating system do you use?

**Comment by CpdnCristiano** [comment]
@jonataslaw windows 10

**Comment by jonataslaw** [comment]
I suspect it is related to the windows separator in that line
https://github.com/jonataslaw/get_cli/blob/master/lib/commands/impl/create/page/page.dart#L31

Since I don't have windows, I need more information to try the fix.
What folders are created? is the folder inside the module created?

**Comment by CpdnCristiano** [comment]
That was the error presenting
```✖ Unexpected error occurred:
NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: path```

**Comment by dennismensah** [comment]
For those who were able to downgrade, could you pls share details as to how you did it?

**Comment by dennismensah** [comment]
thanks

**Comment by gdelgado11** [comment]
Very well with version 1.3.11 it works great. Thanks for parsing me the command to downgrade. It was good to solve it for future versions. thanks again great job you are doing.
All done!
[✓] Flutter: is fully installed. (Channel master, 1.23.0-14.0.pre.136, on Microsoft Windows [VersiÃ³n 10.0.19041.450], locale es-VE)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.2)
[✓] Chrome - develop for the web: is fully installed.
[✓] Android Studio: is fully installed. (version 4.0)
[✓] VS Code: is fully installed. (version 1.50.0)
[✓] Connected device: is fully installed. (3 available)

In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in .\lib\main.dart.

  1) GetX Pattern (by Kauê)
  2) CLEAN (by Arktekko)
1

Your lib folder is not empty. Are you sure you want to overwrite your project?
WARNING: This action is irreversible

  1) Yes
  2) No
1
✓ Main sample created successfully 👍

Checking project type


Flutter project detected!

app/modules/home/home

Checking project type


Flutter project detected!

✓ main.dart created
✓ app_routes.dart created
✓ app_pages.dart created
✓ home_controller.dart created
✓ home_binding.dart created
✓ home_view.dart created
✓ home route created successfully,
✓ Home page created successfully.

Removing package: "get"

✓ Package: "get" removed!

Running `flutter pub get` …

$ flutter pub get
Running "flutter pub get" in juegox...                              1,5s
✓ Package: get installed!
✓ GetX Pattern structure successfully generated.

There's an update available!
Current installed version: 1.3.11

**Comment by CpdnCristiano** [comment]
log

✓ app_pages.dart created
Unhandled exception:
NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: path
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Structure.model (package:get_cli/core/structure.dart:52:20)
#2      handleFileCreate (package:get_cli/functions/create/create_single_file.dart:12:31)
#3      CreatePageCommand._writeFiles (package:get_cli/commands/impl/create/page/page.dart:66:11)
#4      CreatePageCommand.execute (package:get_cli/commands/impl/create/page/page.dart:44:13)
#5      createInitGetxPattern (package:get_cli/commands/impl/init/flutter/init_getxpattern.dart:31:25)
#6      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#13     createMain (package:get_cli/functions/create/create_main.dart)
#14     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
PS C:\Users\cristianonascimento\Documents>

**Comment by CpdnCristiano** [comment]
FIX on 1.3.13

**Comment by insanebaba** [comment]
**app_pages.dart**  is not updated with new page on creation. Is this supposed to be updated, or we have to manually update it?

**Comment by CpdnCristiano** [comment]
what's your version?

**Comment by CpdnCristiano** [comment]
Describe your error better

**Comment by sylvesterasiedu** [comment]
I get a similar error:  error_unexpected FormatException: Not a properly formatted version string

I am using version: 
░██████╗░███████╗████████╗   ░█████╗░██╗░░░░░░██╗
██╔════╝░██╔════╝╚══██╔══╝   ██╔══██╗██║░░░░░░██║
██║░░██╗░█████╗░░░░░██║░░░   ██║░░╚═╝██║░░░░░░██║
██║░░╚██╗██╔══╝░░░░░██║░░░   ██║░░██╗██║░░░░░░██║
╚██████╔╝███████╗░░░██║░░░   ╚█████╔╝███████╗ ██║
░╚═════╝░╚══════╝░░░╚═╝░░░   ░╚════╝░╚══════╝ ╚═╝

Version: 1.4.1

pages are able to create but app_routes.dart and app_pages.dart are not updated. Since I do not want to modify these two files myself what is the best way around, please?

**Comment by CpdnCristiano** [comment]
@sylvesterasiedu 
edit pubspec.yaml
in
```yaml
get: ^ 3.24.0
```
for
```yaml
get: 3.24.0
```
