### ISSUE TITLE
to install specific version of package there is no documentation

### ISSUE THREAD

**Issue by rustiever** [jonataslaw/get_cli#25]
to install specific version of package
```$ get install package_info:0.4.2```

but this is not mentioned in readme or in any documentation
and also how to give range of version for package?

so shall i add this to readme file?

**Comment by CpdnCristiano** [comment]
not really in the documentation, we will be very happy to receive your cooperation

**Comment by rustiever** [comment]
how to give range of version for package?

**Comment by CpdnCristiano** [comment]
at the moment, there's nothing like that, but I'll work on it.

**Comment by rustiever** [comment]
ok @CpdnCristiano , please assign this issue, i'll work on this

**Comment by rustiever** [comment]
@CpdnCristiano done with the issue please review it and let me know is there any stuff i did wrong

**Comment by jonataslaw** [comment]
closed by https://github.com/jonataslaw/get_cli/pull/32
