### ISSUE TITLE
Page Creation Ends In Error

### ISSUE THREAD

**Issue by dennismensah** [jonataslaw/get_cli#26]
when i enter the page creation command it ends in an error which closes the terminal. The folder is created though.

**Comment by jonataslaw** [comment]
What SO do you use?
What version from get_cli?

**Comment by dennismensah** [comment]
I'm on get cli version 1.3.12 and flutter 1.22

**Comment by dennismensah** [comment]
I'm on windows

**Comment by jonataslaw** [comment]
duplicate of https://github.com/jonataslaw/get_cli/issues/24
