### ISSUE TITLE
Failed to build get_cli Error 

### ISSUE THREAD

**Issue by MehediHasannOvi** [jonataslaw/get_cli#264]
When i Try to Install show this error 
Failed to build get_cli:get:
../AppData/Local/Pub/Cache/hosted/pub.dev/dcli-2.3.0/lib/src/util/wait_for_ex.dart:38:17: Error: Method not found: 'waitFor'.
    value = cli.waitFor<T>(wrapped);
                ^^^^^^^

**Comment by mostcute** [comment]
same err

**Comment by mostcute** [comment]
Flutter 3.22.0 • channel stable

**Comment by srpallab** [comment]
https://github.com/jonataslaw/get_cli/issues/258#issuecomment-2131272850

It worked for me.

**Comment by roiskhoiron** [comment]
same error. 
and i think this [commit](https://github.com/jonataslaw/get_cli/commit/0d643cb8832483f12ea532ab6e1761d3ca25f15a) is solution. The problem is that when we activate get_cli-1.8.4, it depends on dcli-2.3.0 where there is a code error build.

**Comment by MehediHasannOvi** [comment]
Try downloading it directly from github:
flutter pub global activate -s git https://github.com/jonataslaw/get_cli 
@roiskhoiron @srpallab @mostcute @roiskhoiron
