### ISSUE TITLE
Can't load Kernel binary: Invalid kernel binary format version.

### ISSUE THREAD

**Issue by MedwinCorreo** [jonataslaw/get_cli#29]
how to resolve this ? 

i think its in environment variables but , i dont know where is the location of get cli

im using windows 10

![image](https://user-images.githubusercontent.com/16618565/96535412-568e7a00-12c4-11eb-8c92-b40898d681cf.png)

**Comment by jonataslaw** [comment]
move up dart path to above of flutter path. 
And pub\cache\bin too

**Comment by MedwinCorreo** [comment]
get help is working now ., but the cmd immediately close upon entering the command.,

**Comment by jonataslaw** [comment]
Use VsCode/ AndroidStudio terminal or cmd /k

**Comment by MedwinCorreo** [comment]
working now ., thank you <3
