### ISSUE TITLE
Ask whether or not you want to replace existing files when using a command.

### ISSUE THREAD

**Issue by cjamcu** [jonataslaw/get_cli#3]
When using the `get create page: name` command and the page already exists it should ask whether you want to replace the existing page or not. This is most likely applicable to other commands that create files.

**Comment by CpdnCristiano** [comment]
I'll add a --replace
``` dart
get create page:home --replace
```

**Comment by jonataslaw** [comment]
I'm doing an update right now with a selector, I think it's more intuitive to open the menu asking if the user wants to overwrite the file

**Comment by cjamcu** [comment]
> I'm doing an update right now with a selector, I think it's more intuitive to open the menu asking if the user wants to overwrite the file

This is what I was saying. Something that asks if you want to replace or not.

**Comment by jonataslaw** [comment]
Fix on 0.10.3
