### ISSUE TITLE
getx pattern error 

### ISSUE THREAD

**Issue by MedwinCorreo** [jonataslaw/get_cli#30]
clean architecture works smoothly while getx parttern option does not 

![image](https://user-images.githubusercontent.com/16618565/96542832-87c37600-12d5-11eb-9ee6-7d622f94bb2f.png)

**Comment by MedwinCorreo** [comment]
clean architecture works smoothly

**Comment by CpdnCristiano** [comment]
Fix on 1.3.13
Run 
Get update --git

**Comment by MedwinCorreo** [comment]
![image](https://user-images.githubusercontent.com/16618565/96545489-0ff84a00-12db-11eb-898c-dfa17c53bacf.png)

**Comment by MedwinCorreo** [comment]
![image](https://user-images.githubusercontent.com/16618565/96545555-31f1cc80-12db-11eb-8973-b222ae0a400d.png)

**Comment by MedwinCorreo** [comment]
> Fix on 1.3.13
> Run
> Get update --git

![image](https://user-images.githubusercontent.com/16618565/96545579-3fa75200-12db-11eb-84c2-d138f6d9ba3b.png)

**Comment by MedwinCorreo** [comment]
why i cant update it ., with that command  ?

**Comment by jonataslaw** [comment]
Update you dart enviroments. 
on your pubspec 

```
environment:
  sdk: ">=2.8.0 <3.0.0"
```

**Comment by jonataslaw** [comment]
Yeah, it looks like you’ll need to update your dart too, you’re using version 2.7, the current version is 2.10.
In the latest versions there is no need for the dart sdk, if you have the latest version of Flutter, you can uninstall the dart sdk, update your paths and use the Dart of the flutter smoothly

**Comment by MedwinCorreo** [comment]
im currently using the latest version of flutter and dart sdk

![image](https://user-images.githubusercontent.com/16618565/96551714-50f55c00-12e5-11eb-9253-cadf8f257ce1.png)

**Comment by MedwinCorreo** [comment]
all now working with version 1.3.13 
![image](https://user-images.githubusercontent.com/16618565/96553206-67041c00-12e7-11eb-9dd3-48f1d91a842e.png)
