### ISSUE TITLE
Error with single quotes

### ISSUE THREAD

**Issue by luis-cruzt** [jonataslaw/get_cli#31]
Put any key like the following:
`"my_key": "Today's",`

on a json file and generate with:
`get locales assets/locale`

The generated file is wrong and bad formatting on that key due the single quotes.

**Comment by CpdnCristiano** [comment]
Json use only double quotes

**Comment by CpdnCristiano** [comment]
`"my_key": "Today's", `

**Comment by luis-cruzt** [comment]
I'm sorry, actually my json has double quotes, i've edited my issue.

**Comment by CpdnCristiano** [comment]
fix on next version

**Comment by luis-cruzt** [comment]
When is the new version released? Thanks!

**Comment by jonataslaw** [comment]
today

**Comment by luis-cruzt** [comment]
Thank you!

**Comment by ne3Vubeki** [comment]
And where is the fix?

**Comment by luis-cruzt** [comment]
Idk, still waiting

**Comment by luis-cruzt** [comment]
It seems that the update is up, i just executed 'get update' and now my get_cli is on version 1.3.14 instead of 1.3.13
