### ISSUE TITLE
is there any way to achieve auto tab completion while using "get remove `package name`"

### ISSUE THREAD

**Issue by rustiever** [jonataslaw/get_cli#33]
i was wondering is there any way to achieve tab completion while using 
`get remove package-name`
since pubspec.yaml file is there, why can't we just infer that and give this feature to the user

**Comment by jonataslaw** [comment]
Auto complete in bash are nothing useful (they work more like a helper), which makes this feature a lot of work for almost no use, so I'm closing this.
This will not be implemented.
