### ISSUE TITLE
Running get create project:test - Can't create directory

### ISSUE THREAD

**Issue by jjdestef3** [jonataslaw/get_cli#36]
Hi,

Running the get create project:test I get the following error:

ProcessException: No such file or directory
  Command: flutter create --org org.jdallc /Users/johndestefano/IdeaProjects/test

The parent test directory does get created though.

I'm using version 1.3.14 on a Mac.

Thx

**Comment by giullianocht** [comment]
Hi @jjdestef, In the documentation it mentions that it is used like this "get create project", can you try like this?

**Comment by CpdnCristiano** [comment]
you cannot create a project with the name test
`Invalid project name: 'test' - this will conflict with Flutter package dependencies`
