### ISSUE TITLE
Server Project created by get_cli has error.

### ISSUE THREAD

**Issue by atfa** [jonataslaw/get_cli#39]
### error
`
$ get create project
      1) Flutter Project
-->   2) Get Server
? what is the name of the project? newproject
✓ pubspec.yaml created
✓ analysis_options.yaml created
✓ Package: get_server installed!
✓ Package: pedantic installed!
✓ Package: test installed!
✓ Main sample created successfully 👍

Checking project type

Get Server project detected!

Checking project type

Get Server project detected!

./lib/app/modules/home/controllers/home
✓ main.dart created
✓ app_routes.dart created
✓ app_pages.dart created
✓ home_controller.dart created
File "home" created successfully at path: ./lib/app/modules/home/controllers/home
./lib/app/modules/home/bindings/home
✓ home_binding.dart created
File "home" created successfully at path: ./lib/app/modules/home/bindings/home
./lib/app/modules/home/views/home
✓ home_view.dart created
File "home" created successfully at path: ./lib/app/modules/home/views/home
✓ home route created successfully,
✓ Home page created successfully.
✓ GetX Pattern structure successfully generated.

$ cd newproject 

$ pub get
Resolving dependencies... (1.9s)
+ _fe_analyzer_shared 14.0.0
+ analyzer 0.41.1
+ args 1.6.0
+ async 2.4.2
+ auth_header 2.1.4
+ boolean_selector 2.0.0
+ charcode 1.1.3
+ cli_util 0.2.0
+ collection 1.14.13
+ convert 2.1.1
+ coverage 0.14.2
+ crypto 2.1.5
+ file 5.2.1
+ get_core 3.13.0
+ get_instance 3.13.0
+ get_rx 3.13.0
+ get_server 0.90.0
+ getstream 1.2.1
+ glob 1.2.0
+ http 0.12.2
+ http_multi_server 2.2.0
+ http_parser 3.1.4
+ http_server 0.9.8+3
+ intl 0.16.1
+ io 0.3.4
+ jaguar_jwt 2.1.6
+ js 0.6.2
+ logging 0.11.4
+ matcher 0.12.9
+ meta 1.2.4
+ mime 0.9.7
+ node_interop 1.2.1
+ node_io 1.2.0
+ node_preamble 1.4.12
+ package_config 1.9.3
+ path 1.7.0
+ pedantic 1.9.2
+ pool 1.4.0
+ pub_semver 1.4.4
+ shelf 0.7.9
+ shelf_packages_handler 2.0.0
+ shelf_static 0.2.8
+ shelf_web_socket 0.2.3
+ source_map_stack_trace 2.0.0
+ source_maps 0.10.9
+ source_span 1.7.0
+ stack_trace 1.9.6
+ stream_channel 2.0.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ test 1.15.7
+ test_api 0.2.18+1
+ test_core 0.3.11+4
+ typed_data 1.2.0
+ vm_service 4.2.0 (5.5.0 available)
+ watcher 0.9.7+15
+ web_socket_channel 1.1.0
+ webkit_inspection_protocol 0.7.4
+ yaml 2.2.1
Changed 59 dependencies!

$ dart lib/main.dart 
lib/main.dart: Warning: Interpreting this as package URI, 'package:newproject/main.dart'.
lib/app/modules/home/controllers/home_controller.dart:6:19: Error: The getter 'obs' isn't defined for the class 'int'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'obs'.
  final count = 0.obs;
                  ^^^

`

### dart version

`
$ dart --version    
Dart SDK version: 2.12.0-76.0.dev (dev) (Wed Nov 25 05:22:28 2020 -0800) on "linux_x64"
`

**Comment by CpdnCristiano** [comment]
remove content from controller

**Comment by CpdnCristiano** [comment]
corrected in some versions ago.
