### ISSUE TITLE
no matches found: http://URL when using get generate model on home from http://URL

### ISSUE THREAD

**Issue by skakrecha** [jonataslaw/get_cli#41]
not able to generate model from url

**Comment by CpdnCristiano** [comment]
what's your version?

**Comment by skakrecha** [comment]
![Screenshot 2020-12-21 at 1 00 21 PM](https://user-images.githubusercontent.com/3585628/102750853-a0f7aa00-438c-11eb-8d89-ec0739b58cd4.png)
its 1.3.15

**Comment by CpdnCristiano** [comment]
here it worked. is it possible to give me the URL?

**Comment by CpdnCristiano** [comment]
A URL retornar um Json?

**Comment by CpdnCristiano** [comment]
Try to enclose the URL in quotes.

**Comment by skakrecha** [comment]
ok will check once.

**Comment by CpdnCristiano** [comment]
`get generate model from "HTTPS://url"`
