### ISSUE TITLE
Example on how to generate child route

### ISSUE THREAD

**Issue by insanebaba** [jonataslaw/get_cli#44]
Can you elaborate in readme, how to generate child modules based on this update https://github.com/jonataslaw/get_cli/blob/master/CHANGELOG.md#1316 ?

**Comment by CpdnCristiano** [comment]
So that there is no problem, the children routes will be added only in new projects.

**Comment by insanebaba** [comment]
If I have created a view using `get create view:products` and now I want to add /electronic view inside /products . How can I do it using cli? If I use `get create view:electronics on products` , the  _AppPages_ is not updated with child route

**Comment by insanebaba** [comment]
referred link : https://github.com/jonataslaw/getx/blob/master/CHANGELOG.md#3210---big-update

**Comment by CpdnCristiano** [comment]
What's your version of Cli? When did your project start?

**Comment by CpdnCristiano** [comment]
Only new projects are compatible with children route.

**Comment by insanebaba** [comment]
I started it today. 
version:  1.3.16

**Comment by CpdnCristiano** [comment]
in this version the get cli has an error.
I recommend: 
run 
```get install get```
and then
```get init```

**Comment by CpdnCristiano** [comment]
was reported in the issue #43

**Comment by CpdnCristiano** [comment]
be careful not to use get init without backing up if your code

**Comment by insanebaba** [comment]
what is the command to create products -> electronics page ?

**Comment by CpdnCristiano** [comment]
get create page:electronics on products

**Comment by CpdnCristiano** [comment]
but it is necessary to repeat the previous steps

**Comment by insanebaba** [comment]
Thank you It works, The issue was related to windows path. So I used wsl and it works there. Closing the ticket
