### ISSUE TITLE
Error generating capital letters

### ISSUE THREAD

**Issue by ne3Vubeki** [jonataslaw/get_cli#47]
I am generating localization with the command:
`get generate locales assets/locales`
At some point, for properties that have capital letters in the name, when generating into a class, an error occurs in the property name.
`static const error_SERVICE_NOT_AVAILABLE = 'error_SERVICE_NOT_AVAILABLE';`
`'error_s_e_r_v_i_c_e_n_o_t_a_v_a_i_l_a_b_l_e': '推送通知服务不可用。',`
Property names are different.

get_cli 1.4.1

**Comment by CpdnCristiano** [comment]
FIX

**Comment by ne3Vubeki** [comment]
When is the release date?
