### ISSUE TITLE
Error while creating Page

### ISSUE THREAD

**Issue by dhruvanbhalara** [jonataslaw/get_cli#48]
` get create page:booking
✓ File: booking_controller.dart created successfully at path: ./lib\app\modules\booking\\controllers\\booking_controller.dart
✓ File: booking_view.dart created successfully at path: ./lib\app\modules\booking\\views\\booking_view.dart
✓ File: booking_binding.dart created successfully at path: ./lib\app\modules\booking\\bindings\\booking_binding.dart
✖ error_unexpected FormatException: Not a properly formatted version string
`
OS: Windows 10
get_cli Version: 1.4.4

**Comment by CpdnCristiano** [comment]
Edit pusbspec.yaml

In
```yaml
get: ^3.24.0
```
For
```yaml
get: 3.24.0
```

remove the `^

**Comment by dhruvanbhalara** [comment]
Thanks, it Worked
