### ISSUE TITLE
get command conflict with get command of  lwp-request version 2.07 (libwww-perl-5.805) in mac Catalina OS 

### ISSUE THREAD

**Issue by modekano** [jonataslaw/get_cli#55]
Installation successful without any problem, but when run any command it did not work, and show (lwp-request version 2.07) commands

**Comment by CpdnCristiano** [comment]
In version 1.4.4 you can use `getx command`

**Comment by modekano** [comment]
@CpdnCristiano 
stable version now is 1.4.3, is it possible to install 1.4.4??

**Comment by CpdnCristiano** [comment]
run:
`pub global activate -sgit https://github.com/jonataslaw/get_cli.git`

**Comment by modekano** [comment]
@CpdnCristiano
  it work. thanks
