### ISSUE TITLE
Why module have subfolders (binding, controller, view)

### ISSUE THREAD

**Issue by bsolca** [jonataslaw/get_cli#62]
Regarding from the [getx_pattern](https://github.com/kauemurakami/getx_pattern#structure-in-modules) from [kauemurakami](https://github.com/kauemurakami). 

The module folder has not sub folders. Only an optionnal **local_widgets** folder.

I personnaly remove all subfolders (binding, controller, view) to avoid click effort when I'm navigating between files.

Might be create subfolders only with a command flag ?

**Comment by CpdnCristiano** [comment]
now i'm working, i'm a solution where you will add it to your pubspec.yaml:
```yaml
get_cli :
   sub_folder : false
```

**Comment by CpdnCristiano** [comment]
I believe that in the next version it is already available.

**Comment by CpdnCristiano** [comment]
the git version supports this functionality, to use run:
`get update --git`

**Comment by bsolca** [comment]
Under where should the get_cli be located ? And wich pubspec.yaml, the project one ?

**Comment by CpdnCristiano** [comment]
yes, in the pubspec project

**Comment by bsolca** [comment]
It works
