### ISSUE TITLE
Error while create GetX Server

### ISSUE THREAD

**Issue by AnandPilania** [jonataslaw/get_cli#76]
Steps:

1: `get create project:project_name`
2: Select `2` for Server

OUTPUT: `+ File not found in pubspec.yaml`

It will create an empty `project_name` dir

VERSIONS:
```
get_cli 1.4.5
flutter 2.0.5
dart 2.12.3
```
OS: `Win 10.0.19042.906`

**Comment by AnandPilania** [comment]
It will works only after `dart create project_name` => `get create project:project_name`

**Comment by jonataslaw** [comment]
Thanks for providing an alternative solution, but I think this should be fixed, so I am reopening
