### ISSUE TITLE
commands executing twice automatically on terminal. get create page/screen, get generate model

### ISSUE THREAD

**Issue by sagar-uprety** [jonataslaw/get_cli#89]
It seems that the get commands are executing twice in the terminal. 

For example. When I use `get create page:login` , the page is created on the modules folder. However, it tells that the page already exists and if I want to overwrite it or not which was understandable if I had created the page login earlier. But, that's not the case. For every new create page or create screen command, the case is the same and I have enter 2 explicitly to tell get_cli not to overwrite it.

Here are the screenshots of the output in my terminal.

![image](https://user-images.githubusercontent.com/51237312/117623420-7f5c5b00-b193-11eb-9f4c-1e1f1e7702d5.png)

Apparently, same thing happens with get generate model as well and I have to force close the executive with CTRL+C

![image](https://user-images.githubusercontent.com/51237312/117628159-92255e80-b198-11eb-8621-99a1d64bfbb6.png)

Here's my pubspec.yml for reference and I am using get_cli v1.5.0
![image](https://user-images.githubusercontent.com/51237312/117624248-70c27380-b194-11eb-8bdc-451cc78abdcc.png)
![image](https://user-images.githubusercontent.com/51237312/117624419-9e0f2180-b194-11eb-9295-2ed42dad822b.png)

**Comment by ran-dall** [comment]
Duplicate of #65

**Comment by sagar-uprety** [comment]
Yeah. Seems it has something to do with Dart Compiler for Windows.
