### ISSUE TITLE
ShellException(flutter create 

### ISSUE THREAD

**Issue by MedwinCorreo** [jonataslaw/get_cli#95]
error_unexpected ShellException(flutter create --no-pub -i swift -a kotlin --org co.fsef C:\Users\Medness\Desktop\New folder (3)/testss3, exitCode 2, workingDirectory: C:\Users\Medness\Desktop\New folder (3)\testss3)

![image](https://user-images.githubusercontent.com/16618565/119074982-96683c00-ba22-11eb-9b26-32803b856b5e.png)

**Comment by shahirWebo** [comment]
I am also getting same error

**Comment by shahirWebo** [comment]
I don't have idea why this error is coming but i have another alternative way.

- Create project using `flutter create projectname`

- run `get init` now you can use get cli in your project

**Comment by shahirWebo** [comment]
I don't have idea why this error is coming but i have another alternative way.

-     Create project using` flutter create projectname`
-     run `get init` 
-    after that update your pub.yamal file
-    now you can use get cli in your project

**Comment by MedwinCorreo** [comment]
> I don't have idea why this error is coming but i have another alternative way.
> 
> * ```
>   Create project using` flutter create projectname`
>   ```
> * ```
>   run `get init` 
>   ```
> * after that update your pub.yamal file
> * now you can use get cli in your project

yeah thats what im temporarily using too :)
