### ISSUE TITLE
Could not generate User Model code

### ISSUE THREAD

**Issue by alshamynet** [jonataslaw/get_cli#97]
Hello , friends !
I have a `flutter 2.0.6 `release
The `null safty` is supported
I created a file `user.json` in the `assets/models` directory
And I wrote the following code in the file:
```
{
   "name": "",
   "age": 0,
   "friends": ["",""]
}

```
And I run the command below:
`get generate model on home with assets/models/user.json`
This error appeared to me, and I do not know what is the solution?

```
✖  + error_unexpected Could not format because the source could not be parsed:

line 4, column 3 of .: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
  ╷
4 │      List?<String> friends;
  │      ^^^^
  ╵
line 4, column 3 of .: Expected to find ';'.
  ╷
4 │      List?<String> friends;
  │      ^^^^
  ╵
line 4, column 17 of .: A function body must be provided.
  ╷
4 │      List?<String> friends;
  │                    ^^^^^^^
  ╵
line 4, column 17 of .: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
  ╷
4 │      List?<String> friends;
  │                    ^^^^^^^
  ╵
line 4, column 7 of .: The string '?' isn't a user-definable operator.
  ╷
4 │      List?<String> friends;
  │          ^
  ╵
line 4, column 7 of .: Methods must have an explicit list of parameters.
  ╷
4 │      List?<String> friends;
  │          ^
  ╵
line 4, column 7 of .: Operator declarations must be preceded by the keyword 'operator'.
  ╷
4 │      List?<String> friends;
  │          ^
  ╵
line 4, column 8 of .: Types parameters aren't allowed when defining an operator.
  ╷
4 │      List?<String> friends;
  │           ^^^^^^^^
  ╵


Time: 517 Milliseconds

'pub' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by maschulze** [comment]
I have the same issue.

**Comment by marko-mlinarevic** [comment]
same issue here @jonataslaw . Do you have any idea what could it be?

**Comment by jonataslaw** [comment]
It's a easy fix, but I'm very busy this week.

Just insert the "?" If there is no subtype, and if there is, insert it at the end of the subtype, so we have List<String>? instead of List?<String>

this here the code:

https://github.com/jonataslaw/get_cli/blob/master/lib/common/utils/json_serialize/sintaxe.dart#L76-L80

**Comment by alshamynet** [comment]
@jonataslaw 
This problem that happened to me is due to the basic generation of the code in the package `get_cli`
I did not write this list, just applied the example that was mentioned on the `Read Me` page

**Comment by maxzod** [comment]
@jonataslaw  
this should be closed now
